---
apiVersion: v1
kind: Namespace
metadata:
  name: stg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: stg
spec:
  selector:
    matchLabels:
      run: appapi
  # remove replica if using gitops
  replicas: 1
  template:
    metadata:
      labels:
        run: appapi
    spec:
      containers:
      - name: app
        image: fastii/app
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: appapi
  namespace: stg
spec:
  ports:
  - port: 8000
  selector:
    run: appapi
            
            
