name: CI-CD

on:
  push:
    branches: ["main"] 
  #pull_request:
    #branches: ["main"]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Autenticação no Docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.PWD}}
      - name: Construção build e push imagem Docker
        uses: docker/build-push-action@v4.1.4
        with:
          context: ./devops
          file: ./devops/Dockerfile
          push: true
          tags: |
            fastii/app:latest
            fastii/app:${{github.run_number}}
          
  
